# Remove one node each time

given graph _g_ and integer _k_

maintain two list.

1. A list of vertices to be checked, pop a vertex from this list. check if there is a clique of size k in remaining grpah. call it _vertices_to_check_.

1. Vertices that can be removed from graph. call it _vertices_surplus_.

2. Vertices that can not be removed from graph. (After remove it, there no longer has a clique of size _k_), its empty initially. call it _vertices_clique_

first check if _g_ has a clique of size _k_. if no, return empty list.

find all vetices degree less than _k-1_. Add them to _vertices_surplus_, add the other vertices to _vertices_to_check_.

Recursion:

Pop one element V from _vertices_to_check_, a subgraph contain vetices from _vertices_to_check_ + _vertices_clique_

    if subgraph has a clique of size k, add V to _vertices_surplus_.
    
    else add such V to _vertices_clique_. such vertex must be in the only clique of size _k_ in graph g.
    
when _vertices_clique_ has _k_ nodes, we found the clique of size _k_.

Also check `(len(g) - len(vertices_surplus)) <= k`, `(len(vertices_to_check) + len(vertices_clique)) < k`

In [ ]:
import numpy
from FUNCTIONS.clique_problem import clique_problem

def clique(g,k):
#####################################
#                                   #
#  - Input: the adjacency matrix of #
#    a graph with vertices          #
#    {0, 1, ..., n} and a positive  #
#    integer k.                     #
#                                   #
#  - Output: A list of vertices     #
#    forming a clique of size k in  #
#    g if one exists, or []         #
#    otherwise.                     #
#                                   #
#  - Use the function               #
#    clique_problem(g, k) that      #
#    returns 1 if the graph g       #
#    has a clique of size k and 0,  #
#    otherwise.                     #
#                                   #
#  Example:                         #
#            g: [[0 1 1]            #
#                [1 0 1]            #
#                [1 1 0]]           #
#            k: 3                   #
#                                   #
#   clique_problem(g, k): 1         #
#   clique(g, k): [0, 1, 2]         #
#                                   #
#                                   #
#####################################
    # Write yur code here.
    if clique_problem(g, k) == 0:
        return []
    n = len(g)
    # possible node list
    vertices_surplus = []
    vertices_to_check = []
    for v in range(0, n):
        # vertex degree less than k-1, it can not form a clique of size k
        if sum(g[v]) < (k-1):
            vertices_surplus.append(v)
        else:
            vertices_to_check.append(v)
    vertices_clique = []
    return sub_clique(g, k, vertices_surplus, vertices_to_check, vertices_clique)

def sub_clique(g, k, vertices_surplus, vertices_to_check, vertices_clique):
    # print(vertices_surplus, vertices_to_check, vertices_clique)
    if len(vertices_clique) >= k:
        return vertices_clique
    
    if (len(g) - len(vertices_surplus)) <= k:
        # we removed enough vertices from graph, and the remaining vertices must for a clique
        vertices_clique = list(set(list(range(0, len(g)))) - set(vertices_surplus))
        if len(vertices_clique) < k:
            # it means we removed all surplus nodes, but remaining nodes is less than k
            # something is wrong when checking if clique exists
            raise Exception("remaining nodes less than k")
        return vertices_clique
    
    if (len(vertices_to_check) + len(vertices_clique)) < k:
        # it should not happen
        raise Exception("not enough vertices to check")
        
    if len(vertices_to_check) == 0:
        raise Exception("vertices to check exhausted")
        
    one_more_remove = vertices_to_check.pop()
    subg = g[vertices_to_check + vertices_clique, :][:, vertices_to_check + vertices_clique]
    
    if clique_problem(subg, k):
        vertices_surplus.append(one_more_remove)
    else:
        vertices_clique.append(one_more_remove)
        
    return sub_clique(g, k, vertices_surplus, vertices_to_check, vertices_clique)

def main(input):
    return clique(input[0], input[1])

if __name__ == '__main__':
    main(input)

# From big graph to small graph

> this algorithm maybe work too, not verified

given graph _g_ and integer _k_


first check if _g_ has a clique of size _k_. 

find all nodes with degree no less than _k_, to a lis of pssible nodes list, call it _pnl_.

maintain a list of vertices, size _k_, first element is first node from _pnl_, the other filled with 0 initially, call it _sl_.

maintain a list of vertices, mutual neighbor of non-0 element in _sl_, call it _mb_.

iterate over _pnl_, _i_, find all nodes in _pnl_ connected to _i_, make a 2-D list, contain nodes and its neighbours, call it _nl_.
    
recursion:

start from first node in _pnl_, fill it to _sl_, check its neighbor,  
    
    if it contains a clique of size _k_ - len(non-0 element in _sl_): 
        
        go to next node in its neighbor:
            
            check if the mutual neighbor of previous nodes in _sl_ contains a clique of size _k_ - len(non-0 element in _sl_)
                
                when _k_ - len(non-0 element in _sl_) = 2, and mutual neighbor of previous nodes in _sl_ contains a clique size 2, get 2 nodes from mutual neighbors and fill to _sl_, we have found the clique 

    if anytime the mutual neighbor of non-0 element in _sl_ doesn't contain a clique of size _k_ - len(non-0 element in _sl_), the first node in _sl_ +1, and restore other node in _sl_ to 0, start the process again. 
    
    if anytime, mutual neighbor of non-0 element in _sl_ is smaller than _k_ - len(non-0 element in _sl_), start the process again.
    
    if length of (first node in _sl_) to (end of _pnl_) is less than _k_, there can not be a clique of size _k_

In [ ]:
import numpy
from FUNCTIONS.clique_problem import clique_problem
def clique(g,k):
#####################################
#                                   #
#  - Input: the adjacency matrix of #
#    a graph with vertices          #
#    {0, 1, ..., n} and a positive  #
#    integer k.                     #
#                                   #
#  - Output: A list of vertices     #
#    forming a clique of size k in  #
#    g if one exists, or []         #
#    otherwise.                     #
#                                   #
#  - Use the function               #
#    clique_problem(g, k) that      #
#    returns 1 if the graph g       #
#    has a clique of size k and 0,  #
#    otherwise.                     #
#                                   #
#  Example:                         #
#            g: [[0 1 1]            #
#                [1 0 1]            #
#                [1 1 0]]           #
#            k: 3                   #
#                                   #
#   clique_problem(g, k): 1         #
#   clique(g, k): [0, 1, 2]         #
#                                   #
#                                   #
#####################################
    # Write yur code here.
    if clique_problem(g, k) == 0:
        return []
    n = len(g)
    # possible node list
    pnl = []
    for v in range(0, n):
        # vertex degree less than k-1, it can not form a clique of size k
        if sum(g[v]) >= (k-1):
            pnl.append(v)
    # possible node neighbors
    nl = {}
    for w in pnl:
        v_neighbor = numpy.where(g[w] == 1)
        nl[w] = numpy.intersect1d(v_neighbor, pnl)
    # stored nodes, that could form the clique of size k
    # sl = numpy.zeros(k, dtype=int)
    sl = [pnl[0]]
    # mutual neighbor of non-empty node in sl, the first node in sl can be 0,
    # the neighbor of first ndoe always considered
    mb = numpy.array(nl[sl[0]])
    res = sub_clique(g, k, k-1, pnl, nl, sl, mb)
    if res:
        return list(map(int, res))
    else:
        return []
def sub_clique(g, k, l, pnl, nl, sl, mb):
    # print(sl, mb)
    if len(mb) >= l:
        subg = g[mb, :][:, mb]
        if clique_problem(subg, l):
            # todo, check l is 2
            if l == 2:
                for j in range(0, len(mb)-1):
                    sub_mb = mb[j:j+2]
                    if clique_problem(g[sub_mb, :][:, sub_mb], l):
                        return sl + list(sub_mb)
            else:
                next_node_index = pnl.index(sl[-1]) + 1
                sl.append(pnl[next_node_index])
                mb = numpy.intersect1d(mb, nl[next_node_index])
                return sub_clique(g, k, l-1, pnl, nl, sl, mb)
    # no clique in mb
    fni = pnl.index(sl[0]) + 1
    pnl = pnl[fni:]
    if len(pnl) < k:
        # exhausted
        return None
    else:
        sl = [pnl[0]]
        mb = numpy.array(nl[sl[0]])
        return sub_clique(g, k, k-1, pnl, nl, sl, mb)
def main(input):
    return clique(input[0], input[1])
if __name__ == '__main__':
    main(input)